actors:
  abura:
    image_url: /images/actors/abu.png
    name: abura
    url: https://twitter.com/dbym4820
  koike:
    image_url: /images/actors/koike.png
    name: koike
    url: 
author: abura
description: 知的学習支援システムの研究分野に従事する若手による，研究・雑談なんでもありなポッドキャストです．
description_long: 
email: submits.life@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: submitslife
itunes_podcast_url:
keywords: science, engineering, intelligent tutoriing system, learning, education, artificial intelligence, human-computer interaction
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Submits.life
url: https://submits.life
